language: php
php:
  - 7.2.9
sudo: required
dist: trusty

addons:
   chrome: stable

install:
   - cp .env.travis .env
   - travis_retry composer install --no-interaction --prefer-dist --no-suggest

before_script:
  - mysql -e 'create database fakultet;'
  - composer self-update
  - composer update
  - composer require --dev phpunit/phpunit ^7.0
  #- composer install --no-interaction
  - php artisan migrate
  - php artisan db:seed
  - php artisan vendor:publish --provider="JeroenNoten\LaravelAdminLte\ServiceProvider" --tag=assets
  - php artisan vendor:publish --provider="JeroenNoten\LaravelAdminLte\ServiceProvider" --tag=config  
  - php artisan vendor:publish --provider="JeroenNoten\LaravelAdminLte\ServiceProvider" --tag=views 
  - php artisan make:adminlte --force
  # nepotrebno dodati usera jer smo ga vec dodali putem UserSeedera
  #- mysql -e "use fakultet2018; INSERT INTO fakultet2018.users (name, email, email_verified_at, password, remember_token, created_at, updated_at) VALUES('Predrag Mrvic', 'pmrvic@123.com', NULL, '$2y$10$unv5NFvl89zxAhdy5.cnFOae8S01aoFdO73X..qPECtQV5YCrCPSG', 'qwBUkyVl0n5ykKgUfLy67f1pYZt6JrSzQFCgOo4oUv8XcBVXxPB1susHuvRe', '2019-01-08 19:44:24.0', '2019-01-08 19:44:24.0');"
  - google-chrome-stable --headless --disable-gpu --remote-debugging-port=9222 http://localhost &
  - php artisan serve &

script:
  #- vendor/bin/phpunit --debug --bootstrap vendor/autoload.php tests/
  - vendor/bin/phpunit --debug --bootstrap vendor/autoload.php --configuration ./phpunit.xml
  - php artisan dusk
  
deploy:
  provider: pages
  skip-cleanup: true
  local-dir: ./tests/Browser/screenshots
  github-token: dabdbd939757d36c5067d586f8d1bc7a92db2e67
  keep-history: true
  on:
    branch: gh-pages